// Wraps `eleventy --serve` and restarts it whenever a file is added or
// removed under src/content (new/deleted posts). Eleventy's own watcher
// handles edits to existing files fine and stays fast for those - but
// pagination pages for brand-new collection items (e.g. a new Painting
// post) don't reliably get generated by its incremental watch rebuild,
// only by a fresh process start. This restarts automatically instead of
// needing a manual restart every time.

const { spawn } = require("child_process");
const path = require("path");
const chokidar = require("chokidar");

const ELEVENTY_CMD = path.join(__dirname, "..", "node_modules", "@11ty", "eleventy", "cmd.cjs");
const WATCH_PATHS = ["src/content/**/*.md"];

let child = null;
let restarting = false;
let debounceTimer = null;

function startEleventy() {
  child = spawn(process.execPath, [ELEVENTY_CMD, "--serve"], {
    stdio: "inherit",
    windowsHide: true,
  });
  child.on("exit", function (code, signal) {
    if (!restarting) {
      console.log("[dev-watch] eleventy exited (code=" + code + " signal=" + signal + ")");
    }
  });
}

function restartEleventy(reason) {
  if (!child) {
    startEleventy();
    return;
  }
  restarting = true;
  console.log("[dev-watch] restarting eleventy (" + reason + ")");
  child.once("exit", function () {
    restarting = false;
    startEleventy();
  });
  child.kill();
}

function scheduleRestart(reason) {
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(function () {
    restartEleventy(reason);
  }, 400);
}

startEleventy();

var watcher = chokidar.watch(WATCH_PATHS, { ignoreInitial: true });
watcher.on("add", function (filePath) {
  scheduleRestart("added " + filePath);
});
watcher.on("unlink", function (filePath) {
  scheduleRestart("removed " + filePath);
});

process.on("SIGINT", function () {
  if (child) child.kill();
  process.exit(0);
});
